### ISSUE TITLE
Unable to call a private class method from instance

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#12717]
## Bug Report

```cr
class Foo
  private def self.bar
    "bar"
  end
  
  def initialize
    pp self.class.bar
  end
end
 
# Error: private method 'bar' called for Foo.class
Foo.new
```

I would have expected this to work given I'm using the private class method internally within the type itself.

**Comment by asterite** [comment]
What happens if you make it `protected`?

`private` means you can only call the method without an explicit receiver.

**Comment by asterite** [comment]
Ah, I see. I might have approved #5995 out of tiredness pushing against it, so I guess this might also happen at some point :-D

**Comment by Fryguy** [comment]
This also doesn't work in Ruby for the same reasons listed above.

```
Traceback (most recent call last):
	2: from foo.rb:14:in `<main>'
	1: from foo.rb:14:in `new'
foo.rb:9:in `initialize': private method `bar' called for Foo:Class (NoMethodError)
```

**Comment by straight-shoota** [comment]
> But if you make it `protected` then it could be used outside of it.

Well, not really. `protected` methods can only be called from the same namespace. `private` methods can only be called from the same instance.

**Comment by Blacksmoke16** [comment]
Right, but even if its scoped to the same namespace, some other type outside of the one its defined in could still use it. Which I'm wanting to prevent by only having it accessible within the type itself.

**Comment by asterite** [comment]
> some other type outside of the one its defined in could still use it

What's the problem with that?

**Comment by Blacksmoke16** [comment]
In practice probably nothing. Just from a reader's POV seeing `protected` would imply it could be used, whereas `private` is more clear in that its an internal thing. I suppose you could add a comment or something to make it more clear, but having the compiler enforce that is a bit better IMO.

Just feels like a workaround. Like what's the point of having `private` instance methods at all in that case?

**Comment by straight-shoota** [comment]
Visibility modifiers just designate visibility. They do not express anything about purpose or in which situations they should be called.
Those are different categories, but tend to be washed together. I don't think this is great, but that's what we have 🤷 

For example, not all internal methods can actually be `private` because they need to be callable from outside an instance. A typical expression of that is `:nodoc:`. On the other end, private methods can have more than internal use only being part of an API that subtypes need to implement (but still being callable only from the same instance).

**Comment by Blacksmoke16** [comment]
My mental model has been:

* `public` - The public API, what the user should be using, stable API
* `protected` - The internal API, what the library itself uses to support the public API, using these methods + public API within the library code internally
* `private` - Implementation details, specific to a particular type, subject to change/refactoring

So to me it just feels like you should be able to use private class methods internally within the type they are defined in. Just like you'd use private instance methods internally within the type they are defined in.

**Comment by Fryguy** [comment]
I think the subtlety is conflating the class instance (Foo itself) and a regular instance (Foo.new).  If you treat those as two independent things, then, even by your definition, a private class method on Foo shouldn't be accessible by an instance of Foo, just as you wouldn't expect an instance of Bar to access private class methods on Foo. 

Note that I'm not saying I disagree with you.  I've always wanted a way, even in Ruby, to have something like C++'s `friend`, so you can give private access to another related object.

**Comment by straight-shoota** [comment]
@Blacksmoke16 Yeah, I see that this mental model basically suggests itself.
But it's incomplete. There's no space for implementation details that need to be available to be called from outside the instance. An example for this might be a helper used for implementing the comparison operator (`<=>`). You would need to call that on both `self` and `other`, thus it can't be private. But it would still be an implementation detail.

**Comment by Blacksmoke16** [comment]
Yea, as you said, that's when you'd have to get into `# :nodoc:` on public methods. In which case none of this really helps you anyway. But, for me at least, I haven't had to do that all that often, at least compared to just leveraging the standard visibility methods. 

> I think the subtlety is conflating the class instance (Foo itself) and a regular instance (Foo.new).

This is a good point. It _does_ make sense if that's how you view it. Question then is should there be an exception to allow the latter to use the former's private methods?

**Comment by asterite** [comment]
I think visibility in Ruby is extremely different from to other OOP languages like C# and Java. I'm not sure I like Ruby's one that much,and that's why at least protected exists in Crystal and not in Ruby. Protected is like "almost private, except some close types can access it". In my mind it doesn't matter if a few more close types that aren't intended to access the method can actually access it. After all you are in charge of the code. And users of the library won't be able to use that method.

That said, I wouldn't mind changing private to mean "instance type or metaclass type can access it".

**Comment by vlazar** [comment]
> `private` means you can only call the method without an explicit receiver.

Is that true only for private class methods? You can call private instance methods with explicit `self.`

```cr
class A
  def call_private_on_explicit_self
    self.private_method
  end
  private def private_method
    "works"
  end
end

A.new.call_private_on_explicit_self # => "works"
```

**Comment by vlazar** [comment]
> `private` methods can only be called from the same instance.

I feel that phrased like that, it has some room for confusion.

You could pass the same instance to public method and try call a private method on this object, but it won't work despite instance being the same.

```cr
class A
  def call_private_on_explicit(instance)
    instance.private_method
  end

  private def private_method
  end
end

a = A.new
a.call_private_on_explicit(a) # Error: private method 'private_method' called for A
```

**Comment by asterite** [comment]
I think we made an exception for `self`. It seems Ruby did the same thing so we just copied them 🤷

**Comment by vlazar** [comment]
Hmmm...

```
% ruby -e 'class A; def call_private_on_explicit; self.class.private_method; end; private; def self.private_method; p "works"; end; end; A.new.call_private_on_explicit'
"works"
```

```
% crystal eval 'class A; def call_private_on_explicit; self.class.private_method; end; private def self.private_method; p "works"; end; end; A.new.call_private_on_explicit'
Showing last frame. Use --error-trace for full trace.

error in line 1
Error: private method 'private_method' called for A.class
```

**Comment by Blacksmoke16** [comment]
> You could pass the same instance to public method and try call a private method on this object, but it won't work despite instance being the same.

PHP actually has this:
![image](https://user-images.githubusercontent.com/12136995/200389594-6be23520-54e0-4b92-916c-eae348fe548c.png)

https://www.php.net/manual/en/language.oop5.visibility.php

This could help with https://github.com/crystal-lang/crystal/issues/12717#issuecomment-1302686765 as you could then do something like:
```cr
class Foo
  include Comparable(self)
  
  def initialize(@name : String); end
  
  def <=>(other : Foo)
    self.normalized_name <=> other.normalized_name
  end
  
  private def normalized_name
    @name.upcase
  end
 end
 ```
 and not need to revert to using public `:nodoc:` methods.

**Comment by vlazar** [comment]
> and not need to revert to using public `:nodoc:` methods.

There is still `protected` which would also work

**Comment by asterite** [comment]
@vlazar `private` in Ruby doesn't work for class methods. You have to use `private_class_method`.

**Comment by vlazar** [comment]
@asterite Thanks! That's one of the tiny bits of Ruby I don' like, and sometimes forget. Fixed my original comment.
