### ISSUE TITLE
Unwinding is slow on WSL

### ISSUE THREAD

**Issue by devnote-dev** [crystal-lang/crystal#14358]
```crystal
puts caller
```

The above code takes significantly longer to run on Ubuntu WSL2 compared to Windows:

```sh
$ crystal build test.cr
$ time ./test
["test.cr:1:6 in '__crystal_main'", "/home/devonte/.local/share/crimson/crystal/1.11.2/share/crystal/src/crystal/main.cr:129:5 in 'main_user_code'", "/home/devonte/.local/share/crimson/crystal/1.11.2/share/crystal/src/crystal/main.cr:115:7 in 'main'", "/home/devonte/.local/share/crimson/crystal/1.11.2/share/crystal/src/crystal/main.cr:141:3 in 'main'", "/lib/x86_64-linux-gnu/libc.so.6 in '??'", "/lib/x86_64-linux-gnu/libc.so.6 in '__libc_start_main'", "./test in '_start'", "???"]        
./test  0.34s user 0.26s system 8% cpu 7.207 total
```

```ps1
C:\> crystal.exe build test.cr
C:\> Measure-Command { .\test.exe }
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 171
Ticks             : 1718276
TotalDays         : 1.98874537037037E-06
TotalHours        : 4.77298888888889E-05
TotalMinutes      : 0.00286379333333333
TotalSeconds      : 0.1718276
TotalMilliseconds : 171.8276
```

At first this difference doesn't look like much, but with larger projects the time becomes problematic. I initially discovered this on an Athena project I'm working on where it varied between 20-30 seconds when an exception backtrace was unwinded, however this doesn't seem to happen on actual Linux distros.

**Comment by HertzDevil** [comment]
Is this exclusive to Crystal? Do other languages exhibit a similar speed difference?

**Comment by devnote-dev** [comment]
I believe so, although I wasn't entirely sure how to test this (using go 1.19):

```go
package main

import (
	"fmt"
	"runtime/debug"
)

func fail() {
	panic("uh oh!")
}

func main() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Printf("%s\n", err)
			fmt.Printf("%+v\n", string(debug.Stack()))
		}
	}()

	fail()
}
```

```sh
$ go build test.go
$ time ./test
uh oh!
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
main.main.func1()
        /mnt/c/Users/user/Documents/arachnid/test.go:16 +0x70
panic({0x48a3e0, 0x4b84e0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
main.fail(...)
        /mnt/c/Users/user/Documents/arachnid/test.go:9
main.main()
        /mnt/c/Users/user/Documents/arachnid/test.go:20 +0x4a

./test  0.00s user 0.02s system 8% cpu 0.254 total
```
```ps1
C:\> go build test.go
C:\> Measure-Command { .\test.exe }
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 89
Ticks             : 898827
TotalDays         : 1.04030902777778E-06
TotalHours        : 2.49674166666667E-05
TotalMinutes      : 0.001498045
TotalSeconds      : 0.0898827
TotalMilliseconds : 89.8827
```

**Comment by straight-shoota** [comment]
I tried exactly the same, also on WSL2 with Ubuntu and I see a very different performance:

```console
$ time ./caller
[".test/caller.cr:1:6 in '__crystal_main'", "/home/linuxbrew/.linuxbrew/Cellar/crystal/1.11.2/share/crystal/src/crystal/main.cr:129:5 in 'main_user_code'", "/home/linuxbrew/.lin
uxbrew/Cellar/crystal/1.11.2/share/crystal/src/crystal/main.cr:115:7 in 'main'", "/home/linuxbrew/.linuxbrew/Cellar/crystal/1.11.2/share/crystal/src/crystal/main.cr:141:3 in 'ma
in'", "/lib/x86_64-linux-gnu/libc.so.6 in '??'", "/lib/x86_64-linux-gnu/libc.so.6 in '__libc_start_main'", "./caller in '_start'", "???"]
./caller  0,01s user 0,02s system 97% cpu 0,030 total
```

```console
$  Measure-Command { .\caller.exe }
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 150
Ticks             : 1509557
TotalDays         : 1,7471724537037E-06
TotalHours        : 4,19321388888889E-05
TotalMinutes      : 0,00251592833333333
TotalSeconds      : 0,1509557
TotalMilliseconds : 150,9557
```

**Comment by ysbaddaden** [comment]
It could be interesting to see what happens with `--no-debug` or calling `caller` twice and measure the second call only, to see which of unwinding the symbols or decoding the debug tables from the executable takes time.

**Comment by devnote-dev** [comment]
WSL no debug:

```crystal
["./test in 'Exception::CallStack::unwind:Array(Pointer(Void))'", "./test in 'Exception::CallStack#initialize:Array(Pointer(Void))'", "./test in 'Exception::CallStack::new:Exception::CallStack'", "./test in 'caller:Array(String)'", "./test in '__crystal_main'", "./test in 'Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil'", "./test in 'Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32'", "./test in 'main'", "/lib/x86_64-linux-gnu/libc.so.6 in '??'", "/lib/x86_64-linux-gnu/libc.so.6 in '__libc_start_main'", "./test in '_start'", "???"]
00:00:00.119909135
```

Windows no debug:

```crystal
["test.exe +81046 in '??'", "test.exe +80942 in '??'", "test.exe +80906 in '??'", "test.exe +70889 in '??'", "test.exe +5464 in '??'", "test.exe +727929 in '??'", "test.exe +727706 in '??'", "test.exe +66073 in '??'", "test.exe +66355 in '??'", "test.exe +786700 in '??'", "C:\\WINDOWS\\System32\\KERNEL32.DLL +75133 in 'BaseThreadInitThunk'", "C:\\WINDOWS\\SYSTEM32\\ntdll.dll +371288 in 'RtlUserThreadStart'"]
00:00:00.099170400
```

WSL 2nd caller:

```crystal
["test.cr:3:23 in '__crystal_main'", "/home/devonte/.local/share/crimson/crystal/1.11.2/share/crystal/src/crystal/main.cr:129:5 in 'main_user_code'", "/home/devonte/.local/share/crimson/crystal/1.11.2/share/crystal/src/crystal/main.cr:115:7 in 'main'", "/home/devonte/.local/share/crimson/crystal/1.11.2/share/crystal/src/crystal/main.cr:141:3 in 'main'", "/lib/x86_64-linux-gnu/libc.so.6 in '??'", "/lib/x86_64-linux-gnu/libc.so.6 in '__libc_start_main'", "./test in '_start'", "???"]
00:00:00.001196319
```

Windows 2nd caller:

```crystal
["test.cr:3 in '__crystal_main'", "C:\\Users\\user\\AppData\\Local\\Programs\\Crystal-Installer\\src\\crystal\\main.cr:129 in 'main_user_code'", "C:\\Users\\user\\AppData\\Local\\Programs\\Crystal-Installer\\src\\crystal\\main.cr:115 in 'main'", "C:\\Users\\user\\AppData\\Local\\Programs\\Crystal-Installer\\src\\crystal\\main.cr:141 in 'main'", "C:\\Users\\user\\AppData\\Local\\Programs\\Crystal-Installer\\src\\crystal\\system\\win32\\wmain.cr:37 in 'wmain'", "d:\\a01\\_work\\12\\s\\src\\vctools\\crt\\vcstartup\\src\\startup\\exe_common.inl:288 in '__scrt_common_main_seh'", "C:\\WINDOWS\\System32\\KERNEL32.DLL +75133 in 'BaseThreadInitThunk'", "C:\\WINDOWS\\SYSTEM32\\ntdll.dll +371288 in 'RtlUserThreadStart'"]
00:00:00.001635100
```

WSL no debug & 2nd caller:

```crystal
["./test in 'Exception::CallStack::unwind:Array(Pointer(Void))'", "./test in 'Exception::CallStack#initialize:Array(Pointer(Void))'", "./test in 'Exception::CallStack::new:Exception::CallStack'", "./test in 'caller:Array(String)'", "./test in '__crystal_main'", "./test in 'Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil'", "./test in 'Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32'", "./test in 'main'", "/lib/x86_64-linux-gnu/libc.so.6 in '??'", "/lib/x86_64-linux-gnu/libc.so.6 in '__libc_start_main'", "./test in '_start'", "???"]
00:00:00.001927353
```

Windows no debug & 2nd caller:

```crystal
["test.exe +81046 in '??'", "test.exe +80942 in '??'", "test.exe +80906 in '??'", "test.exe +70889 in '??'", "test.exe +5469 in '??'", "test.exe +727929 in '??'", "test.exe +727706 in '??'", "test.exe +66073 in '??'", "test.exe +66355 in '??'", "test.exe +786700 in '??'", "C:\\WINDOWS\\System32\\KERNEL32.DLL +75133 in 'BaseThreadInitThunk'", "C:\\WINDOWS\\SYSTEM32\\ntdll.dll +371288 in 'RtlUserThreadStart'"]
00:00:00.001013300
```

**Comment by ysbaddaden** [comment]
Thanks! So unwinding ain't the problem, same for mapping symbols to a file:line. The problem seems to be the parsing of the executable debug lines section?

**Comment by devnote-dev** [comment]
I can take a look at it later today. 👍

**Comment by HertzDevil** [comment]
Also there is a dramatic difference depending on whether the executable is located on the Windows filesystem or not. You could build a single `test` or compiler executable and it will behave differently as soon as you move it across the two filesystems. That PR somewhat closes the gap but is still not perfect.

**Comment by devnote-dev** [comment]
There seems to be a significant improvement but this is based on the above statement – I couldn't get a Linux artifact of the build so I'm comparing using the Windows one.

**Comment by HertzDevil** [comment]
Correction: the original slowless is not due to `#seek`, but rather due to the `#size` call inside `File#read_at`.
