### ISSUE TITLE
Probleman on upgrading via Brew upgrade

### ISSUE THREAD

**Issue by xdougx** [crystal-lang/crystal#2447]
```
$ brew upgrade
==> Upgrading 5 outdated packages, with result:
manastech/crystal/shards 0.5.3, solr 5.5.0, sqlite 3.12.1, typesafe-activator 1.3.7, unixodbc 2.3.4
==> Upgrading manastech/crystal/shards
==> Downloading https://github.com/ysbaddaden/shards/archive/v0.5.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/shards-0.5.3.tar.gz
==> crystal build -o bin/shards src/shards.cr --release
Last 15 lines from /Users/douglas/Library/Logs/Homebrew/shards/01
Last 15 lines from /Users/douglas/Library/Logs/Homebrew/shards/01.crystal:

    parse(ARGV) { |parser| yield parser }
    ^~~~~

in ./src/cli.cr:23: instantiating 'OptionParser:Class#parse!()'

    OptionParser.parse! do |opts|
                 ^~~~~~

in ./src/cli.cr:24: undefined method 'working_directory' for Dir:Class

      path = Dir.working_directory
                 ^~~~~~~~~~~~~~~~~



READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/manastech/homebrew-crystal/issues

Error: 422 Unprocessable Entity
Validation Failed
```

**Comment by kumpelblase2** [comment]
shards v. 0.5.3 seems old and -as far as I know- shards ships with `crystal-lang` on homebrew. Do you have `crystal-lang` installed or how did you install it?

**Comment by xdougx** [comment]
Yes, i have crystal installed as `Crystal 0.15.0 (Wed Apr 13 13:30:43 UTC 2016)`
but i cant update/install shards at this moment

```
$ brew uninstall shards
Uninstalling /usr/local/Cellar/shards/0.5.1... (6 files, 522.3K)
```

Even installing a clean version:

```
$ brew install shards
==> Installing shards from manastech/crystal
==> Downloading https://github.com/ysbaddaden/shards/archive/v0.5.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/shards-0.5.3.tar.gz
==> crystal build -o bin/shards src/shards.cr --release
Last 15 lines from /Users/douglas/Library/Logs/Homebrew/shards/01.crystal:

    parse(ARGV) { |parser| yield parser }
    ^~~~~

in ./src/cli.cr:23: instantiating 'OptionParser:Class#parse!()'

    OptionParser.parse! do |opts|
                 ^~~~~~

in ./src/cli.cr:24: undefined method 'working_directory' for Dir:Class

      path = Dir.working_directory
                 ^~~~~~~~~~~~~~~~~



READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/manastech/homebrew-crystal/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
Validation Failed
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
	from /usr/local/Library/Homebrew/utils.rb:615:in `open'
	from /usr/local/Library/Homebrew/utils.rb:648:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:681:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:251:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:247:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:292:in `dump'
	from /usr/local/Library/brew.rb:147:in `rescue in <main>'
	from /usr/local/Library/brew.rb:29:in `<main>'
```
what could be happaning when ruby try to download with open-uri

**Comment by kumpelblase2** [comment]
Can you just install `crystal-lang` and check if `shards` is available (e.g. `which shards` or `shards --version`)? Because [this](https://github.com/crystal-lang/homebrew-crystal/blob/master/crystal-lang.rb#L14) should install shards with it.

**Comment by xdougx** [comment]
```
$ which shards
/usr/local/bin/shards
```

**Comment by kumpelblase2** [comment]
Alright, then you don't need to install it separately. You should be fine like this from here.

**Comment by xdougx** [comment]
Check this out:
```
lrwxr-xr-x    1 douglas  admin     40 Apr 13 10:33 shards -> ../Cellar/crystal-lang/0.15.0/bin/shards
```
shards is inside crystal-lang
