### ISSUE TITLE
YAML errors not reporting proper line numbers

### ISSUE THREAD

**Issue by plukevdh** [crystal-lang/crystal#2585]
Using latests release, though this issue existed in 0.15.0 as well. Given a malformated yaml like so:

```yaml
---
level_one:
- name: "test"
    attributes:
      one: "broken"
```
 
I would expect the line number in the error to be `3:3`, but instead I get the following:

```
Unexpected event: NONE at 0:0 (YAML::ParseException)
[4298684274] *CallStack::unwind:Array(Pointer(Void)) +82
[4298684177] *CallStack#initialize<CallStack>:Array(Pointer(Void)) +17
[4298684136] *CallStack::new:CallStack +40
[4298742473] *Exception@Exception#initialize<YAML::ParseException, String>:CallStack +41
[4298742399] *YAML::ParseException#initialize<YAML::ParseException, String, UInt64, UInt64>:CallStack +143
[4298742220] *YAML::ParseException::new<String, UInt64, UInt64>:YAML::ParseException +124
[4298740077] *YAML::Parser#raise<YAML::Parser, String>:NoReturn +61
[4298740008] *YAML::Parser#unexpected_event<YAML::Parser>:NoReturn +88
[4298738747] *YAML::Parser#parse_node<YAML::Parser>:(Array(YAML::Type) | Hash(YAML::Type, YAML::Type) | String | Nil) +267
[4298739262] *YAML::Parser#parse_mapping<YAML::Parser>:Hash(YAML::Type, YAML::Type) +142
[4298738732] *YAML::Parser#parse_node<YAML::Parser>:(Array(YAML::Type) | Hash(YAML::Type, YAML::Type) | String | Nil) +252
[4298738995] *YAML::Parser#parse_sequence<YAML::Parser>:Array(YAML::Type) +147
[4298738688] *YAML::Parser#parse_node<YAML::Parser>:(Array(YAML::Type) | Hash(YAML::Type, YAML::Type) | String | Nil) +208
[4298739308] *YAML::Parser#parse_mapping<YAML::Parser>:Hash(YAML::Type, YAML::Type) +188
[4298738732] *YAML::Parser#parse_node<YAML::Parser>:(Array(YAML::Type) | Hash(YAML::Type, YAML::Type) | String | Nil) +252
[4298738405] *YAML::Parser#parse_document<YAML::Parser>:(Array(YAML::Type) | Hash(YAML::Type, YAML::Type) | String | Nil) +37
[4298738335] *YAML::Parser#parse<YAML::Parser>:YAML::Any +111
[4298737953] *YAML::parse<String>:YAML::Any +33
[4298658737] __crystal_main +1745
[4298666984] main +40
```

Run using the following command:

`cr eval 'require "yaml"; YAML.parse File.read("broken.yml")'`

My current version of libyaml is 0.16.0 and it appears that Ruby's `psych` does not suffer from this issue:

```
ruby -ryaml -e 'YAML.parse(File.open("broken.yml"))'
/Users/plukevdh/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych.rb:370:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 3 column 3 (Psych::SyntaxError)
	from /Users/plukevdh/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
	from /Users/plukevdh/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych.rb:318:in `parse'
	from -e:1:in `<main>'
```

**Comment by plukevdh** [comment]
❤️
