### ISSUE TITLE
Improve backtraces

### ISSUE THREAD

**Issue by mperham** [crystal-lang/crystal#2785]
While porting some Ruby code to Crystal, I ran some specs and found that the error backtraces were missing huge chunks of code frames.  It was very painful to debug the issues due to incomplete backtraces, often missing line numbers.  Here's an example:

```
       cast to Int failed
       [4525793250] *CallStack::unwind:Array(Pointer(Void)) +82
       [4525793153] *CallStack#initialize<CallStack>:Array(Pointer(Void)) +17
       [4525793112] *CallStack::new:CallStack +40
       [4526322281] *Exception@Exception#initialize<TypeCastError, String>:CallStack +41
       [4526322205] *TypeCastError#initialize<TypeCastError, String>:CallStack +29
       [4526322148] *TypeCastError::new<String>:TypeCastError +100
       [4525582152] ~proc(HTTP::Server::Context -> String)@./src/sidekiq/web.cr:88 +2072
       [4525566338] ~proc(HTTP::Server::Context -> String)@./libs/kemal/kemal/route.cr:10 +66
       [4526712301] *Kemal::RouteHandler#process_request<Kemal::RouteHandler, HTTP::Server::Context>:HTTP::Server::Context +125
       [4526712157] *Kemal::RouteHandler#call<Kemal::RouteHandler, HTTP::Server::Context>:HTTP::Server::Context +93
       [4525709936] *get<String, Nil, Nil>:(HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | Nil) +192
       [4526809829] */Users/mike/src/sidekiq.cr/spec/web_spec.cr#get<String>:(HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | Nil) +21
       [4525728014] ~proc( -> Void)@./spec/web_spec.cr:286 +2718
       [4525503099] *it<String, String, Int32, &( -> Void)>:(Array(Spec::Result) | Bool | Nil) +427
       [4525704007] ~proc( -> Void)@./spec/web_spec.cr:4 +1831
       [4525994230] *Spec::RootContext::describe<String, String, Int32, &( -> Void)>:Spec::Context+ +310
       [4525501977] *describe<String, String, Int32, &( -> Void)>:Spec::Context+ +9
       [4525431833] __crystal_main +31705
       [4525483016] main +40
```

Note the top element in my code: sidekiq/web.cr:88:

```ruby
get "/busy" do |x|
  ecr("busy")
end
```

Great.  ECR pushes the entire template into the code.  None of it is visible in backtrace.  So I throw in some `raise "boom"` in the template to bisect down to this line:

```ruby
    <% x.processes.each do |process| %>
 ```

This calls Sidekiq::ProcessSet#each:

```ruby
    def each
      Sidekiq.redis do |conn|
        prcs = conn.smembers("processes")
        procs = [] of String
        prcs.each { |x| procs << x.as(String) }
        procs.sort!

        # We're making a tradeoff here between consuming more memory instead of
        # making more roundtrips to Redis, but if you have hundreds or thousands of workers,
        # you'll be happier this way
        results = conn.pipelined do |ppp|
          procs.each do |key|
            ppp.hmget(key, "info", "busy", "beat", "quiet")
          end
        end.as(Array(Redis::RedisValue))

        results.each do |x|
          packet = x.as(Array(Redis::RedisValue))
          info = packet[0].as(String)
          busy = packet[1].as(Int).to_i64  # <========= ACTUAL BUG
          beat = packet[2].as(String).to_f64
          quiet = packet[3]?.to_s == "true"

          hash = JSON.parse(info).as_h
          hash["busy"] = busy
          hash["beat"] = beat
          hash["quiet"] = quiet
          yield Process.new(hash)
        end
      end

      nil
    end
```

This is one example of how debugging is painful today due to huge gaps in error backtraces.  The equivalent Ruby backtrace would have 4-6 frames between these two lines and make for a 20 second bugfix instead of a 20 minute bughunt.

```
       [4526322148] *TypeCastError::new<String>:TypeCastError +100
       [4525582152] ~proc(HTTP::Server::Context -> String)@./src/sidekiq/web.cr:88 +2072
```

Are there any easy wins to improve the situation?

**Comment by asterite** [comment]
In master the "cast failed" exception now includes the file and line where it happens, so that's an improvement :-)

The main issue here is that blocks are always inlined so that's why call like `each` don't appear in the stack trace: they aren't calls.

I don't know if there's a way to fake the stack trace or similar, when generating code. I remember @waj told me something like that is possible when generating debug info, so in the future compiling with `--debug` maybe will solve this.

Not inlining block is far from trivial. We'd have to create procs for every block, closure local variables and pass them to those procs. I also think that will make things not just slow, maybe horribly slow (imagine that happening every time you iterate an array, or do `5.times`), but of course without trying it's impossible to know.

Another possibility is to let `raise` receive `__FILE__` and `__LINE__` and set that to an Exception's information, and show that on error. This is a small improvement but doesn't work well when an exception is raised inside someone else's code, for example doing `[1, 2][3]` would show the file and line for Array, which isn't very interesting... and forwarding file and line number for every array access doesn't sound good/efficient either.

**Comment by asterite** [comment]
Another side note: did you try searching `.as(Int)` to find the bug more easily? Searching in sidekiq.cr for that shows me 4 matches, so adding `puts` in those locations would have spotted the problem very quickly.

(of course the above is not an excuse to not improve the language 😊 )

**Comment by mperham** [comment]
Well, keep in mind if you make it a non-default switch, I can turn it on for those times when I need precise traces, e.g. when targeting individual spec failures: `crystal spec --slow file.cr:line`.  I couldn't care less about a 10x speed loss if my debugging goes from 20 minutes to 20 seconds.

For this issue, I made up the error.  The actual cause was nil data in Redis that didn't cast correctly to a String.

**Comment by paulcsmith** [comment]
Another thing that might be nice would be to include what it got when it failed to cast. That might be a separate issue though

**Comment by asterite** [comment]
@paulcsmith That's already fixed too, the error now is "failed to cast String to Int"

**Comment by paulcsmith** [comment]
@asterite I meant including the actual value. Like `failed to cast "my_string" (String) to Int`. Sometimes including the actual value received can help debugging. But maybe it already does that?

**Comment by ysbaddaden** [comment]
Note that `gdb` or `lldb` often help to debug. They need a binary compiled with `--debug` and can even access the file and line numbers (thought the line number is often a little off) for better traces. You may even display the source code with `gdb -tui`. I won't help with inlined blocks, and support for displaying variables is missing (except for basic primitives), but it may help following what's happening and where. For example:

```
$ crystal build --debug foo.cr
$ gdb -tui foo
(gdb) break foo.cr:5
(gdb) run
(...)
Breakpoint 1, add () at foo.cr:6
(gdb) bt
#0  add () at foo.cr:6
#1  0x0000000000423424 in __crystal_main () at foo.cr:8
#2  0x0000000000425ba9 in main () at .crystal/macro73205920.cr:11
(gdb) step
main () at .crystal/macro73205920.cr:3
(gdb) 
```

Note: the fact that gdb can access the file:line information means that we should be capable to do the same for exception backtraces in Crystal (but as @waj said earlier: it's hard).

**Comment by paulcsmith** [comment]
@ysbaddaden that's really handy information. Thank you so much!

**Comment by rdp** [comment]
OK I was referred here from the mailing list.

Doing some initial experimentation, I don't get back line numbers even from simple code that doesn't use blocks, ex:

```
def go1
  go2
end

def go2
  raise "boom"
end

go1
```

output:

```
./test
boom (Exception)
[4532799234] *CallStack::unwind:Array(Pointer(Void)) +82
[4532799137] *CallStack#initialize:Array(Pointer(Void)) +17
[4532799096] *CallStack::new:CallStack +40
[4532779209] *raise<Exception>:NoReturn +25
[4532779169] *raise<String>:NoReturn +17
[4532791299] *go2:NoReturn +19
[4532791273] *go1:NoReturn +9
[4532777806] __crystal_main +926
[4532790984] main +40

```

I assume this is the same problem or should I file a different issue here?
Thanks!

**Comment by RX14** [comment]
@rdp see https://github.com/crystal-lang/crystal/pull/3303

**Comment by ysbaddaden** [comment]
@rdp not exactly, this issue is more about inlined blocks. Line numbers in exceptions is coming, as RX14 pointed, in #3303.

**Comment by codenoid** [comment]
```
Unexpected EOF (Exception)
0x531cc7: *CallStack::unwind:Array(Pointer(Void)) at ??
0x65aa5c: read_byte! at /home/ayam/Documents/kafarahapp/educode/lib/mysql/src/mysql/read_packet.cr 40:18
0x65abde: read_int at /home/ayam/Documents/kafarahapp/educode/lib/mysql/src/mysql/read_packet.cr 65:5
0x6c42d2: read at /home/ayam/Documents/kafarahapp/educode/lib/mysql/src/mysql/packets.cr 13:7
0x6bafb9: read_packet at /home/ayam/Documents/kafarahapp/educode/lib/mysql/src/mysql/connection.cr 63:14
0x6bab01: initialize at /home/ayam/Documents/kafarahapp/educode/lib/mysql/src/mysql/connection.cr 22:19
0x6ba80f: new at /home/ayam/Documents/kafarahapp/educode/lib/mysql/src/mysql/connection.cr 4:3
0x6ba77d: build_connection at /home/ayam/Documents/kafarahapp/educode/lib/mysql/src/mysql/driver.cr 4:5
0x6c7880: build_resource at /home/ayam/Documents/kafarahapp/educode/lib/db/src/db/pool.cr 255:3
0x6c77f6: initialize at /home/ayam/Documents/kafarahapp/educode/lib/db/src/db/pool.cr 17:34
0x6c64ac: *DB::Pool(T)::new:initial_pool_size:max_pool_size:max_idle_pool_size:checkout_timeout:retry_attempts:retry_delay<Int32, Int32, Int32, Float64, Int32, Float64, &Proc(DB::Connection+)>:DB::Pool(DB::Connection+) at ??
0x6b6a42: initialize at /home/ayam/Documents/kafarahapp/educode/lib/db/src/db/database.cr 50:7
0x6b684d: new at /home/ayam/Documents/kafarahapp/educode/lib/db/src/db/database.cr 43:5
0x6af506: build_database at /home/ayam/Documents/kafarahapp/educode/lib/db/src/db.cr 140:5
0x6af4ee: build_database at /home/ayam/Documents/kafarahapp/educode/lib/db/src/db.cr 136:5
0x6af4d6: open at /home/ayam/Documents/kafarahapp/educode/lib/db/src/db.cr 104:5
0x4ebf16: __crystal_main at /home/ayam/Documents/kafarahapp/educode/src/educode.cr 16:1
0x4ffdf9: main at /opt/crystal/src/main.cr 12:15
0x7f85af34a830: __libc_start_main at ??
0x4ea489: _start at ??
0x0: ??? at ??
```

```
    def connection_pool_options(params : HTTP::Params)
      {
        initial_pool_size:  params.fetch("initial_pool_size", 200).to_i,
        max_pool_size:      params.fetch("max_pool_size", 0).to_i,
        max_idle_pool_size: params.fetch("max_idle_pool_size", 200).to_i, # socket closed
        checkout_timeout:   params.fetch("checkout_timeout", 5.0).to_f,
        retry_attempts:     params.fetch("retry_attempts", 1).to_i,
        retry_delay:        params.fetch("retry_delay", 1.0).to_f,
      }
    end
```

> https://github.com/crystal-lang/crystal-db/issues/58

**Comment by Sija** [comment]
@codenoid https://github.com/crystal-lang/crystal/issues/1077#issuecomment-313645715

**Comment by codenoid** [comment]
-_- . this comment written before #1077

**Comment by Sija** [comment]
yeah, consequences of double-posting in wrong places, well...

**Comment by alexanderadam** [comment]
I'm not sure whether this is the place where my problem belongs to (I mean "Improve backtraces" is a broad field).

However, I [just created an issue on spec2.cr about missing the most relevant part of the callstack](https://github.com/waterlink/spec2.cr/issues/62) and now I saw this issue here and think it might be caused by something of the core part of crystal.
Because `spec2.cr` isn't doing anything relevant with the callstack and even if I print `CallStack.new.printable_backtrace` within the expectation method the important line is missing. So it might be something in `CallStack` (or at least related), right?

**Comment by rdp** [comment]
My particular example is working now, at least I get "most" line numbers, thanks! :)

**Comment by rdp** [comment]
reduced example (I think):

```
$ cat 2785.cr 
require "ecr"
class Greeting
  ECR.def_to_s "greeting.ecr"
end
Greeting.new().to_s
$ cat greeting.ecr 
1
2
3
<%= raise "boom" %>
$ crystal 2785.cr 
Unhandled exception: boom (Exception)
  from 2785.cr:4:5 in 'to_s' # it lost the location within greeting.ecr file
  from /usr/share/crystal/src/object.cr:96:7 in 'to_s'
  from 2785.cr:7:1 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:97:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:86:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:106:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

**Comment by rdp** [comment]
I think crystal can generate "expanded" files with all the macros, maybe it could base, or optionally base,  the backtrace off the temp expanded file??
