### ISSUE TITLE
HTTP::Client.post crashes on arm when inside a Kemal route 

### ISSUE THREAD

**Issue by helaan** [crystal-lang/crystal#6954]
The code is crosscompiled from an amd64 device to arm-linux-gnueabihf using the compiler flags `--cross-compile --target armv7a-unknown-linux-gnueabihf`. Running the code natively on amd64 works fine, as does removing the Kemal block. I'm not sure what happens exactly what changes when you put it in a route block, I believe it should be possible to generate a crash that does not require Kemal. I've repeated the situation multiple times: each time the program crashes immediately and with the same error message. 

Host machine: Gentoo GNU/Linux, Amd64 laptop, LLVM 6.0.1, Crystal 0.26.1
Target machine: Gentoo GNU/Linux, Raspberry Pi 2 (armv7a-hardfloat-linux-gnueabi), LLVM 6.0.1, Crystal source code v0.26.1, make deps ran (needed for libcrystal.a).

Reproduction steps:
1. On the host machine: `crystal build crpostcrash.cr --cross-compile --target=armv7a-unknown-linux-gnueabihf`
1. Transfer the crpostcrash.o file to the target machine
1. On the target machine:  (command printed in host compile step, paths adapted for my situation)
```
cc crpostcrash.o -o 'crpostcrash'  -rdynamic -lyaml  -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lpcre -lm -lgc -lpthread crcompiler/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib
```
4. Run the created binary
1. On the target machine: `curl localhost:3000`

Result:
The compiled binary exits with code 7 and the following is printed on stdout/err:
```
[development] Kemal is ready to lead at http://0.0.0.0:3000
Invalid memory access (signal 7) at address 0x74a0c3e4
[0x12d124] ???
[0x6b0e4] __crystal_sigfault_handler +72
```
Additionally, running the program through gdb shows the following:
```
Program received signal SIGBUS, Bus error.
0x76fd9e9c in ?? () from /lib/ld-linux-armhf.so.3
(gdb) info s
#0  0x76fd9e9c in ?? () from /lib/ld-linux-armhf.so.3
#1  0x76fe270c in ?? () from /lib/ld-linux-armhf.so.3
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

Code:
```
require "http"
require "kemal"

get "/" do
	response = HTTP::Client.post("https://httpbin.org/post",
#		headers: HTTP::Headers{"Content-Type" => "application/json"},
#		body: %[{"test":123}]
	)
#	"#{response.status_code}: #{response.body}"
end

Kemal.run
```

**Comment by helaan** [comment]
Still is strange for me: according to `/proc/cpuinfo`, the machine supports NEON, so it should not have issues with these commands. Adding my usual CFLAGS to the cc call didn't solve it.

I'm still not entirely convinced by this new route: the errors are severe enough and I wondered whether my variant that worked also suffered from this issue. So I commented out the Kemal stuff, leaving just the Net::HTTP call that I confirmed working earlier and sent it down the same route. I received the same set of errors. Either all of the code that errors out is not reachable, which would be worthy of a seperate bug, or my route is broken. For now, I'm going for the latter.

I'm not ruling out FPU issues, but I think the llvm-ir route is a red herring

**Comment by straight-shoota** [comment]
Closing. Due to age of the issue and no additional reports, stability enhancements in platform support probably fixed the bug.
