### ISSUE TITLE
badssl_spec fails some examples

### ISSUE THREAD

**Issue by rdp** [crystal-lang/crystal#8466]
# Submitting questions

Running crystal badssl_spec.cr:

about 5 tests fail, or hang
```

$ crystal -v
Crystal 0.31.1 [0e2e1d067] (2019-09-30)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu

crystal/spec/manual $ ./badssl_spec 
.E.E.E.
hang, or really slow
```

seems to fail tests that end with "with verification disabled"
  should connect to expired.badssl.com with verification disabled

**Comment by rdp** [comment]
note to self: those ??? backtraces have filenames (but nothing else) in gdb wonder how gdb gets the filenames..
```
#1  0x000055555567682f in write () at /usr/share/crystal/src/io/buffered.cr:128
#2  0x00005555555ca555 in -> () at /usr/share/crystal/src/openssl/bio.cr:31
#3  0x00007ffff7cfea33 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#4  0x00007ffff7cfeed3 in BIO_write () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#5  0x00007ffff7cfd02a in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#6  0x00007ffff7cff3a7 in BIO_ctrl () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#7  0x00007ffff7f6d3bd in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#8  0x00007ffff7f71e0f in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#9  0x00007ffff7f6c89a in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#10 0x00007ffff7f589c4 in SSL_do_handshake () from /lib/x86_64-linux-gnu/libssl.so.1.1
#11 0x000055555569b3cf in initialize:context:hostname () at /usr/share/crystal/src/openssl/ssl/socket.cr:32
```.
