### ISSUE TITLE
at_exit is not triggered by SIGINT and SIGTERM

### ISSUE THREAD

**Issue by sudo-nice** [crystal-lang/crystal#8687]
This code will not print on CTRL-C, which might be [unexpected]:

```crystal
at_exit { print "Exiting" }
sleep
```
Currently, it can be handled, but feels awkward:

```crystal
at_exit { print "Exiting" }
Signal::INT.trap { exit }
sleep
```
---
Crystal 0.32.1 [41bd18fbe] (2019-12-18)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu

[unexpected]: https://github.com/crystal-lang/crystal/issues/8493#issuecomment-555917453

**Comment by asterite** [comment]
Same behavior in Ruby... so probably not a bug?

**Comment by sudo-nice** [comment]
@asterite
It prints for me with Ruby 2.6.

```
^CExitingTraceback (most recent call last):
	1: from ./t.rb:5:in `<main>'
./t.rb:5:in `sleep': Interrupt
```

**Comment by asterite** [comment]
Oh, you are right, I missed it because it was mixed with the other message.

**Comment by asterite** [comment]
I guess Ruby has a default SIGINT

**Comment by sudo-nice** [comment]
I've just noticed, Ruby triggers `at_exit` on SIGTERM too.
Would be nice to have it that way with Crystal.

**Comment by bcardiff** [comment]
👍 on my side. As long as at_exit has a way opt-out the sigint and/or sigterm registration.

**Comment by sudo-nice** [comment]
I've been overtaken by some concerns about this issue.
What if one wants to distinguish between normal program exiting and exiting because of receiving SIGTERM or SIGINT? Currently, it can easily be handled:

```crystal
at_exit { do_normal_exit_routine }
Signal::INT { do_siging_routine }
Signal::TERM { do_sigterm_routine }
```

But if `at_exit` is going to catch all of those, one'd have to use flags?

```crystal
enum TrackSignal
  SIGINT
  SIGTERM
end

module Exit
  class_property signal : TrackSignal
end

at_exit do
  case Exit.signal
  when TrackSignal::SIGINT  then do_sigint_routine
  when TrackSignal::SIGTERM then do_sigterm_routine
  else                           do_normal_exit_routine
  end
end

Signal::INT.trap { Exit.signal = TrackSignal::SIGINT }
Signal::TERM.trap { Exit.signal = TrackSignal::SIGTERM }

```
So, despite being more verbose sometimes, the current implementation is more explicit and clear. Sorry for wasting your time.

**Comment by asterite** [comment]
If you want to distinguish those cases you can handle sigint. If not, I think it's fine to run at_exit handlers as expected.

**Comment by sudo-nice** [comment]
@asterite please, consider this:


```crystal
def should_run_only_at_normal_exit
  # ...
end

def should_run_only_at_sigint
  # ...
end

at_exit { should_run_only_at_normal_exit }
Signal::INT.trap { should_run_only_at_sigint }
```
How to prevent the `should_run_only_at_normal_exit` method from being triggered by `SIGINT` then?

**Comment by bcardiff** [comment]
I was suggesting something like the following to have the flexibility

```crystal
at_exit(sig_int: false, sig_term: false) { run_only_at_normal_exit }
at_exit { run_on_normal_int_or_term }
at_exit(sig_int: true, sig_term: true) { run_on_normal_int_or_term } # same as above

Signal::INT.trap { run_only_at_int }
Signal::TERM.trap { run_only_at_term }

at_exit(sig_term: true) { run_on_normal_or_term }
at_exit(sig_int: true) { run_on_normal_or_int }
```

**Comment by straight-shoota** [comment]
I'd lay out the relationship in the opposite direction: Call `exit(run_at_exit_handlers: false)` from signal handlers that are not supposed to execute `at_exit` handlers. This could have other use cases as well.

However, I'm not entirely sure if we really need an overload for `exit` or just let the application provide and use appropriate methods instead of calling top-level `exit` directly.

**Comment by bcardiff** [comment]
The motivation is that users can use `at_exit`, not mention signals at all and the block will be executed even if the app exits due to a ctrl+c. It seems a good _default_ for me.

**Comment by asterite** [comment]
If Ruby doesn't allow doing what you want, why do we need to do something different?

Nobody seems to have problems with how it works in Ruby. `at_exit` should run at exit regardless of how the program exits.

I think doing the same thing as Ruby is fine.

**Comment by sudo-nice** [comment]
>If Ruby doesn't allow doing what you want, why do we need to do something different?

Ruby is great, but not ideal. Crystal is already different (and better) at some areas, so why not keeping it that way?

**Comment by ysbaddaden** [comment]
IMO having default SIGINT and SIGTERM traps that merely call `exit` is a good behavior. That would allow to gracefully terminate the program, running all `at_exit` callbacks.

I think adding configuration to run an `at_exit` callback is unrequited complexity and mixes unrelated concepts together: signals may lead to exit, but exit itself has nothing to do with signals.

I agree with @straight-shoota that we could instead have a mean to immediately exit, without calling any `at_exit` callbacks at all.

If you need to do something special for SIGINT, then trap SIGINT and call `exit` (or not). Same for SIGTERM. Either with an `run_at_exit_handlers` argument or a new `exit!` method.

Here is an example to gracefully terminate on normal exit or SIGINT + immediate termination on a second SIGINT (Ctrl+C):

```crystal
at_exit { do_some_cleanup() }

sigint = Atomic::Flag.new

Signal::INT.trap do
  if sigint.test_and_set
    puts "Type Ctrl+C again to force termination"
    exit
  else
    exit run_at_exit_handlers: false
  end
end
```

**Comment by RX14** [comment]
I'm in total agreement with @ysbaddaden: let's add default `SIGINT` and `SIGTERM` traps, and then add `exit!` to allow exiting without running `at_exit` hooks.

**Comment by daliborfilus** [comment]
My use case for signal traps is to NOT EXIT at that moment, but exit gracefuly later (e.g. in daemons), like this:

```crystal
running = true

Signal::INT.trap { running = false }

while running
  # do something hardcore... which MUST NOT be interrupted willy nilly
  sleep 5
end
```

Calling `at_exit` at "trap time" would be completely unexpected.
In my example above, `at_exit` handler will get called at the end anyway. 
Am I correct?

Having default traps call `exit` is completely fine by me.

**Comment by ysbaddaden** [comment]
@daliborfilus When you trap a signal, you replace any previous definition with your own, overriding any default behavior.

**Comment by straight-shoota** [comment]
https://github.com/crystal-lang/crystal/pull/13568 was reverted in https://github.com/crystal-lang/crystal/pull/13673 due to complications mentioned in https://github.com/crystal-lang/crystal/issues/13672

> Before https://github.com/crystal-lang/crystal/pull/13568, the signal was not trapped and thus would lead directly to exit the process without any involvement of the Crystal runtime.
Now we're trapping SIGINT and SIGTRAP for the handlers to call Crystal's exit routine. But the handler execution is decoupled from the trap. When it receives a signal, it writes it to a pipe and that pipe is then read from the Signal loop fiber which then executes the handler. During compilation the main fiber is occupied with calculations and offers no chance for the signal loop fiber to run.

**Comment by hmood501** [comment]
> This code will not print on CTRL-C, which might be [unexpected]:
> 
> ```crystal
> at_exit { print "Exiting" }
> sleep
> ```
> Currently, it can be handled, but feels awkward:
> 
> ```crystal
> at_exit { print "Exiting" }
> Signal::INT.trap { exit }
> sleep
> ```
> ---
> Crystal 0.32.1 [41bd18fbe] (2019-12-18)
> 
> LLVM: 8.0.0
> Default target: x86_64-unknown-linux-gnu
> 
> [unexpected]: https://github.com/crystal-lang/crystal/issues/8493#issuecomment-555917453
> 

644f45243467018aeb89d0bd10fc0d742eb18519

**Comment by hmood501** [comment]
> I'd lay out the relationship in the opposite direction: Call `exit(run_at_exit_handlers: false)` from signal handlers that are not supposed to execute `at_exit` handlers. This could have other use cases as well.
> 
> However, I'm not entirely sure if we really need an overload for `exit` or just let the application provide and use appropriate methods instead of calling top-level `exit` directly.

**Comment by m-o-e** [comment]
Adding my 2 cents here as I've been dabbling with signals lately.

> `at_exit` should run at exit regardless of how the program exits.

Yes. Strong agree.

> When you trap a signal, you replace any previous definition with your own, overriding any default behavior.

This is an additional problem.

In Ruby-land [Signal.trap returns the previous handler](https://stackoverflow.com/a/57749753),
so you can safely chain them.

Crystal currently has no equivalent to this.

This is problematic when for example a shard needs
to add a signal-handler. As of today it has no way to
preserve (or even detect) an already attached handler.

I'd like to propose the following syntax to enable signal handler chaining:

```crystal
Signal::INT.trap do
  puts "Trap 1"
  exit
end

Signal::INT.trap do |previous_handler|
  puts "Trap 2"
  previous_handler.call
end
```

Output on signal:
```
Trap 2
Trap 1
```

**Comment by straight-shoota** [comment]
@m-o-e That's a good point but outside the scope of this issue. I've created https://github.com/crystal-lang/crystal/issues/13803 to track this.

**Comment by stakach** [comment]
we also have a solution for sigterm et al. #13694
